# Generated by Django 5.0.1 on 2024-01-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_gender_alter_userprofile_blood_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_available',
            field=models.BooleanField(),
        ),
    ]
