# Generated by Django 5.0.1 on 2024-01-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userprofile_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
