# Generated by Django 5.0.4 on 2024-04-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_userprofile_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to='oldBindu/profilePictures'),
        ),
    ]
