# Generated by Django 5.0.4 on 2024-04-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactus_created_at_contactus_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='oldBindu/services'),
        ),
    ]
