# Generated by Django 5.0.2 on 2024-03-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='event_date',
        ),
    ]
