# Generated by Django 5.0.4 on 2024-04-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_date_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='oldBindu/events'),
        ),
    ]
